<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="YS.Knife.Hosting" Version="2.0.2" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\src\YS.Knife.Mapper.Core\YS.Knife.Mapper.Core.csproj" />
      <ProjectReference Include="..\..\src\YS.Knife.Mapper.Impl.FlyTiger\YS.Knife.Mapper.Impl.FlyTiger.csproj" />
    </ItemGroup>
</Project>
