# 使用.NET 6 SDK镜像直接运行应用
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS runtime
WORKDIR /app

# 复制整个项目目录
COPY . .

# 修改项目文件，将TargetFrameworks改为TargetFramework并仅保留net6.0
RUN sed -i 's/<TargetFrameworks>net8.0<\/TargetFrameworks>/<TargetFramework>net6.0<\/TargetFramework>/' /app/example/ExposeApiDemo/ExposeApiDemo.csproj

# 回到主项目
WORKDIR /app/example/ExposeApiDemo


RUN dotnet publish -c Release -o /app -f net6.0

# 暴露端口
EXPOSE 80

# 运行应用
ENTRYPOINT ["dotnet", "/app/ExposeApiDemo.dll"]