<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ToolCommandName>ys.knife.cli</ToolCommandName>
        <RootNamespace>YS.Knife.Cli</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    </ItemGroup>

</Project>
