<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
    <ItemGroup>
        <Using Include="YS.Knife" />
        <PackageReference Include="YS.Knife.Core" Version="2.0.2" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\YS.Knife.LayerValue.Core\YS.Knife.LayerValue.Core.csproj" />
      <ProjectReference Include="..\YS.Knife.LogicRoles.Core\YS.Knife.LogicRoles.Core.csproj" />
    </ItemGroup>
</Project>
