<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
      <ProjectReference Include="..\..\src\YS.Knife.Generators.ExposeApi\YS.Knife.Generators.ExposeApi.csproj">
          <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
          <OutputItemType>Analyzer</OutputItemType>
      </ProjectReference>
    <ProjectReference Include="..\..\src\YS.Knife.AppRes.Impl.EFCore\YS.Knife.AppRes.Impl.EFCore.csproj" />
    <ProjectReference Include="..\..\src\YS.Knife.Mapper.Impl.FlyTiger\YS.Knife.Mapper.Impl.FlyTiger.csproj" />
  </ItemGroup>
    <ItemGroup>
        <PackageReference Include="YS.Knife.Hosting.Web" Version="2.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.3" />
    </ItemGroup>
</Project>
