name: basic
on:
  push:
    branches:
      - "*"
      - "!master"
    tags-ignore:
      - "*"  
jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
    - name: 01 Checkout Code
      uses: actions/checkout@v4
    - name: 02 Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          6.0.x
          9.0.x
    - name: 03 Build with dotnet
      run: dotnet build