name: build
on:
  push:
    branches:
      - "*"  
  pull_request:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 01 Checkout Code
      uses: actions/checkout@v4
    - name: 02 Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          6.0.x
          9.0.x
    - name: 03 Restore Dotnet Tool
      run: dotnet tool restore
    - name: 04 Check Code Format
      run: dotnet format --verify-no-changes 
    - name: 05 Build with dotnet
      run: dotnet build
    - name: 06 Setup docker compose
      uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2' # the full version of `docker-compose` command
    - name: 07 Count Test Projects
      run: echo TEST_PROJ_COUNT=$(ls -l test |grep "^d"|wc -l) >> $GITHUB_ENV
    - name: 08 Run Unit test
      if: env.TEST_PROJ_COUNT>0
      run: dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[*Test]*"